name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: choco install ffmpeg --confirm

      - name: Set up Python and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller fastapi uvicorn yt-dlp nest_asyncio ffmpeg-python

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --hidden-import=yt_dlp --hidden-import=ffmpeg choclotube.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: choclotube-exe
          path: dist/*.exe
