name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python and Build EXE
        run: |
          choco install ffmpeg --confirm
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          venv\Scripts\pip install pyinstaller fastapi uvicorn nest_asyncio yt-dlp ffmpeg-python
          venv\Scripts\python -m pyinstaller --onefile --hidden-import=yt_dlp --hidden-import=ffmpeg tu_script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: dist/*.exe
